name: movie_challange
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  dio: ^5.4.2+1
  easy_debounce: ^2.0.3
  fade_shimmer: ^2.2.0
  flutter:
    sdk: flutter
  flutter_animator: ^3.2.2
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  infinite_scroll_pagination: ^4.0.0
  json_annotation: ^4.8.1
  logger: ^2.2.0
  path_provider: ^2.1.2

dev_dependencies:
  analyzer: ^6.4.1
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter_intl:
  enabled: true
  arb_dir: lib/src/core/config/l10n
  output_dir: lib/src/core/config/l10n/generated

flutter:
  uses-material-design: true
